# Generated by Django 3.2.25 on 2025-10-13 04:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_url', models.URLField(help_text='Starting URL that initiated the crawl')),
                ('download_directory', models.TextField(help_text="Absolute path to the crawl's download folder")),
                ('max_pages', models.PositiveIntegerField(blank=True, null=True)),
                ('max_pdfs', models.PositiveIntegerField(blank=True, null=True)),
                ('pages_crawled', models.PositiveIntegerField(default=0)),
                ('pdfs_downloaded', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DownloadedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_url', models.TextField(help_text='Direct URL used to retrieve the PDF')),
                ('source_page', models.TextField(blank=True, help_text='Web page URL where the PDF link was found')),
                ('filename', models.CharField(max_length=255)),
                ('stored_path', models.TextField(help_text='Filesystem path where the PDF is stored')),
                ('file_size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('download_method', models.CharField(blank=True, max_length=32)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='crawler.crawlrun')),
            ],
            options={
                'ordering': ['-downloaded_at', 'id'],
            },
        ),
    ]
