# Generated by Django 5.2.6 on 2025-11-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crawler", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="downloadeddocument",
            name="tags",
            field=models.TextField(
                blank=True,
                help_text="Comma-separated informative tags from the source page",
            ),
        ),
    ]
